load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fill in oncall here @nocommit")

python_library(
    name = "weighted_sampler",
    srcs = ["weighted_sampler.py"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/pypi/numpy:numpy",
        "fbsource//third-party/pypi/torch:torch",
    ],
)
